/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ClientDAO } from './clientDAO';


export interface CompteDAO { 
    id?: number;
    typeCompte?: CompteDAO.TypeCompteEnum;
    numeroCpt?: string;
    solde?: number;
    codePin?: string;
    client?: ClientDAO;
}
export namespace CompteDAO {
    export type TypeCompteEnum = 'EPARGNE' | 'COURANT';
    export const TypeCompteEnum = {
        Epargne: 'EPARGNE' as TypeCompteEnum,
        Courant: 'COURANT' as TypeCompteEnum
    };
}


