/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface RegisterRequest { 
    nom?: string;
    prenom?: string;
    dateNais?: string;
    adresse?: string;
    sexe?: RegisterRequest.SexeEnum;
    numeroTel?: string;
    couriel?: string;
    nationalite?: string;
    username?: string;
    motDePasse?: string;
}
export namespace RegisterRequest {
    export type SexeEnum = 'MASCULIN' | 'FEMININ';
    export const SexeEnum = {
        Masculin: 'MASCULIN' as SexeEnum,
        Feminin: 'FEMININ' as SexeEnum
    };
}


